version: '3'

services:
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "app:app"
    env_file: 
      - ./app/.env
    volumes:
      - ./app/:/flasktasklist/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./app/.env
    ports:
      - 5432:5432

volumes:
  postgres_data: